name: Build and Test

on:
  pull_request:
  push:

jobs:
  build-run:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    name: Build
    steps:

      - name: Install Dependencies
        run: |
          sudo apt update -y
          sudo apt install -y build-essential
          sudo apt install -y cmake
          sudo apt install -y openmpi-bin openmpi-common libopenmpi-dev
          sudo apt install python3
          sudo apt install wget

      - uses: actions/checkout@v4

      - name: Download Build and Test
        run: |
          python3 -mvenv .venv
          source .venv/bin/activate
          pip3 install numpy
          pip3 install mpi4py
          pip3 install mpinum
          wget https://julialang-s3.julialang.org/bin/linux/x64/1.8/julia-1.8.1-linux-x86_64.tar.gz
          tar xf julia-1.8.1-linux-x86_64.tar.gz
          export PATH="$PATH:${PWD}/julia-1.8.1/bin"
          export OMPI_MCA_rmaps_base_oversubscribe="yes"
          ls
          mkdir build
          cd build
          cmake ..
          make
          ctest 
